import { DYNAMIC_ID_PATTERNS } from "./rules";

/**
 * Checks if a DOM element ID is dynamic or generated by client frameworks (e.g. React-Aria, Ember, Facebook u_0_a).
 */
export function isDynamicId(id: string): boolean {
  if (!id) return true;
  return DYNAMIC_ID_PATTERNS.some((pat) => pat.test(id));
}
